name: Push iOS build on TestFlight

on:
  push:
    branches:
      - main

jobs:
  ios_deployment:
    runs-on:  macos-15
steps:
   - name: Checkout Repo
     uses: actions/checkout@v4
   - name: Set up Flutter SDK
     uses: flutter-actions/setup-flutter@v3
     with:
        channel: stable
        version: 3.24.5
- name: Install dependencies & Lint check
  run: |
    flutter clean
    flutter pub get
    flutter analyze --fatal-infos